version: '3'

services:
  brain-hike:
    image: unfaiyted/brain-hike
    container_name: brain-hike
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - webserver
  faiyt-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: unfaiyted/faiyt-dev
    container_name: faiyt-dev
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - webserver
  faiyt-api:
    image: unfaiyted/faiyt-api
    container_name: faiyt-api
    environment:
      - NODE_ENV=production
    ports:
      - 4000:4000
    restart: unless-stopped
    volumes:
      - ./config/:/config
    depends_on:
      - webserver
  webserver:
    image: linuxserver/swag
    container_name:  webserver
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config/:/config
    environment:
      - EMAIL=miller.l.dane@gmail.com
      - URL=faiyt.dev
      - SUBDOMAINS=www,api,brain-hike
      - VALIDATION=http
      - TZ=Europe/London
      - PUID=0
      - PGID=0
